// 此文件由 Rust 生成，禁止手改。

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	getSnapshot: (payload: EmptyPayload) => __TAURI_INVOKE<RuntimeSnapshotDto>("get_snapshot", { payload }),
	listAgents: (payload: EmptyPayload) => __TAURI_INVOKE<AgentDto[]>("list_agents", { payload }),
	updateAgentConfig: (payload: UpdateAgentConfigPayload) => __TAURI_INVOKE<AgentDto>("update_agent_config", { payload }),
	listChannelAccounts: (payload: EmptyPayload) => __TAURI_INVOKE<ChannelListDto>("list_channel_accounts", { payload }),
	beginChannelLogin: (payload: BeginChannelLoginPayload) => __TAURI_INVOKE<BeginChannelLoginResultDto>("begin_channel_login", { payload }),
	submitChannelLoginCode: (payload: SubmitChannelLoginCodePayload) => __TAURI_INVOKE<LoginSessionDto>("submit_channel_login_code", { payload }),
	logoutChannelAccount: (payload: ChannelAccountIdPayload) => __TAURI_INVOKE<MutationAcceptedDto>("logout_channel_account", { payload }),
	enableChannelAccount: (payload: ChannelAccountIdPayload) => __TAURI_INVOKE<ChannelAccountDto>("enable_channel_account", { payload }),
	disableChannelAccount: (payload: ChannelAccountIdPayload) => __TAURI_INVOKE<ChannelAccountDto>("disable_channel_account", { payload }),
	sendTestNotification: (payload: SendTestNotificationPayload) => __TAURI_INVOKE<TestNotificationResultDto>("send_test_notification", { payload }),
	listNotifications: (payload: NotificationFilterPayload) => __TAURI_INVOKE<NotificationListDto>("list_notifications", { payload }),
	getNotificationDetail: (payload: NotificationIdPayload) => __TAURI_INVOKE<NotificationDetailDto>("get_notification_detail", { payload }),
	retryDelivery: (payload: DeliveryIdPayload) => __TAURI_INVOKE<DeliveryDto>("retry_delivery", { payload }),
	getDiagnostics: (payload: EmptyPayload) => __TAURI_INVOKE<DiagnosticsDto>("get_diagnostics", { payload }),
	getSettings: (payload: EmptyPayload) => __TAURI_INVOKE<SettingsDto>("get_settings", { payload }),
	updateSettings: (payload: SettingsDto) => __TAURI_INVOKE<SettingsDto>("update_settings", { payload }),
	setRuntimePaused: (payload: SetRuntimePausedPayload) => __TAURI_INVOKE<RuntimeSummaryDto>("set_runtime_paused", { payload }),
	quitApp: (payload: EmptyPayload) => __TAURI_INVOKE<MutationAcceptedDto>("quit_app", { payload }),
};

/** Events */
export const events = {
	channelLoginChanged: makeEvent<ChannelLoginChangedEvent>("channel.login.changed"),
	deliveryChanged: makeEvent<DeliveryChangedEvent>("delivery.changed"),
	snapshotChanged: makeEvent<SnapshotChangedEvent>("snapshot.changed"),
};

/* Types */
export type AgentCapabilitiesDto = {
	notify: boolean,
	resume: boolean,
	sessionTitle: boolean,
	hookInstaller: boolean,
	replyWindow: boolean,
};

export type AgentDto = {
	id: string,
	displayName: string,
	description: string,
	configSchema: unknown,
	capabilities: AgentCapabilitiesDto,
	enabled: boolean,
	config: unknown,
	health: AgentHealthDto,
};

export type AgentHealthDto = {
	available: boolean,
	detail: SafeErrorDto | null,
};

export type BeginChannelLoginPayload = {
	channelId: string,
	accountKey: string,
};

export type BeginChannelLoginResultDto = {
	channelId: string,
	session: LoginSessionDto,
};

export type BusinessCommand = "get_snapshot" | "list_agents" | "update_agent_config" | "list_channel_accounts" | "begin_channel_login" | "submit_channel_login_code" | "logout_channel_account" | "enable_channel_account" | "disable_channel_account" | "send_test_notification" | "list_notifications" | "get_notification_detail" | "retry_delivery" | "get_diagnostics" | "get_settings" | "update_settings" | "set_runtime_paused" | "quit_app";

export type ChannelAccountDto = {
	id: string,
	channelId: string,
	displayName: string,
	enabled: boolean,
	config: unknown,
	health: ChannelHealthDto,
	lastInboundAt: string | null,
	lastDeliveryAt: string | null,
};

export type ChannelAccountIdPayload = {
	accountId: string,
};

export type ChannelCapabilitiesDto = {
	sendText: boolean,
	receive: boolean,
	replyRouting: boolean,
	editMessage: boolean,
	attachments: boolean,
	markdown: boolean,
	maxTextBytes: number | null,
	inboundModes: string[],
};

export type ChannelDto = {
	id: string,
	displayName: string,
	configSchema: unknown,
	capabilities: ChannelCapabilitiesDto,
	accounts: ChannelAccountDto[],
};

export type ChannelHealthDto = {
	available: boolean,
	stale: boolean,
	detail: SafeErrorDto | null,
};

export type ChannelListDto = {
	channels: ChannelDto[],
};

export type ChannelLoginChangedEvent = {
	accountId: string,
	sessionId: string | null,
	state: LoginSessionStateDto,
	message: string | null,
};

/**  UI 可见错误。这里只允许稳定错误码、用户文案和诊断引用，不允许放原始响应或凭据。 */
export type CommandError = CommandError_Serialize | CommandError_Deserialize;

/**  UI 可见错误。这里只允许稳定错误码、用户文案和诊断引用，不允许放原始响应或凭据。 */
export type CommandError_Deserialize = {
	code: string,
	message: string,
	retryable: boolean,
	diagnosticId: string | null,
};

/**  UI 可见错误。这里只允许稳定错误码、用户文案和诊断引用，不允许放原始响应或凭据。 */
export type CommandError_Serialize = {
	code: string,
	message: string,
	retryable: boolean,
	diagnosticId?: string | null,
};

export type ComponentDto = {
	name: string,
	state: ComponentStateDto,
	detail: SafeErrorDto | null,
};

export type ComponentStateDto = "Starting" | "Running" | "Paused" | "Stopped" | "Failed";

export type DeliveryChangedEvent = {
	deliveryId: string,
	notificationId: string | null,
	state: DeliveryStateDto | null,
};

export type DeliveryDto = {
	id: string,
	notificationId: string,
	channelId: string,
	accountId: string,
	state: DeliveryStateDto,
	externalMessageId: string | null,
	error: SafeErrorDto | null,
	retryable: boolean,
	updatedAt: string,
};

export type DeliveryIdPayload = {
	deliveryId: string,
};

export type DeliveryStateDto = "Pending" | "Sent" | "Failed" | "Unknown" | "Skipped";

export type DiagnosticActionDto = {
	label: string,
	command: BusinessCommand,
	payload: unknown,
};

export type DiagnosticItemDto = {
	code: string,
	level: DiagnosticLevelDto,
	message: string,
	checkedAt: string,
	action: DiagnosticActionDto | null,
};

export type DiagnosticLevelDto = "Normal" | "Waiting" | "Error" | "Paused";

export type DiagnosticsDto = {
	generatedAt: string,
	runtime: RuntimeSummaryDto,
	storage: StorageStatusDto,
	components: ComponentDto[],
	items: DiagnosticItemDto[],
};

export type EmptyPayload = Record<string, never>;

export type HostEvent = "snapshot.changed" | "delivery.changed" | "channel.login.changed";

export type LoginSessionDto = {
	id: string,
	accountId: string | null,
	accountKey: string,
	state: LoginSessionStateDto,
	qrPayload: string | null,
	createdAt: string,
	message: string | null,
	error: SafeErrorDto | null,
};

export type LoginSessionStateDto = "Idle" | "Preparing" | "QrReady" | "WaitingScan" | "NeedVerifyCode" | "WaitingFirstInbound" | "Paired" | "Expired" | "Blocked" | "Failed";

export type MutationAcceptedDto = {
	accepted: boolean,
	id: string | null,
};

export type NotificationDetailDto = {
	notification: NotificationSummaryDto,
	body: string,
	metadata: { [key in string]: string },
	deliveries: DeliveryDto[],
	routeExists: boolean,
};

export type NotificationFilterPayload = {
	agentId: string | null,
	channelId: string | null,
	accountId: string | null,
	deliveryState: DeliveryStateDto | null,
	from: string | null,
	to: string | null,
	query: string | null,
	cursor: string | null,
	limit: number,
};

export type NotificationIdPayload = {
	notificationId: string,
};

export type NotificationListDto = {
	items: NotificationSummaryDto[],
	total: number,
	nextCursor: string | null,
};

export type NotificationSummaryDto = {
	id: string,
	agentId: string,
	sessionId: string | null,
	sessionTitle: string | null,
	title: string,
	preview: string,
	occurredAt: string,
	deliveryStates: DeliveryStateDto[],
};

export type QuietHoursDto = {
	enabled: boolean,
	start: string,
	end: string,
};

export type RuntimeLifecycleStateDto = "Starting" | "Running" | "Paused" | "Stopping" | "Stopped" | "Failed";

export type RuntimeSnapshotDto = {
	runtime: RuntimeSummaryDto,
	overview: SnapshotOverviewDto,
	components: ComponentDto[],
	diagnostics: DiagnosticItemDto[],
};

export type RuntimeSummaryDto = {
	appVersion: string,
	platform: string,
	state: RuntimeLifecycleStateDto,
	paused: boolean,
};

export type SafeErrorDto = {
	code: string,
	message: string,
};

export type SendTestNotificationPayload = {
	accountId: string,
	title: string,
	body: string,
};

export type SetRuntimePausedPayload = {
	paused: boolean,
};

export type SettingsDto = {
	notificationsPaused: boolean,
	quietHours: QuietHoursDto | null,
	cooldownSeconds: number,
	defaultChannelAccountId: string | null,
	replyEnabled: boolean,
	deliveryReceiptEnabled: boolean,
	routeTtlSeconds: number,
	autoStart: boolean,
	startHidden: boolean,
	updateChannel: UpdateChannelDto,
};

export type SnapshotChangedEvent = {
	reason: string,
};

export type SnapshotOverviewDto = {
	storage: StorageStatusDto,
	agents: AgentDto[],
	channels: ChannelAccountDto[],
	recentDeliveries: DeliveryDto[],
};

export type StorageStatusDto = {
	notificationCount: number,
	deliveryCount: number,
	pendingOutboxCount: number,
	recentError: SafeErrorDto | null,
};

export type SubmitChannelLoginCodePayload = {
	sessionId: string,
	code: string,
};

export type TestNotificationResultDto = {
	accepted: boolean,
	delivery: DeliveryDto | null,
};

export type UpdateAgentConfigPayload = {
	agentId: string,
	enabled: boolean | null,
	config: unknown | null,
};

export type UpdateChannelDto = "Stable" | "Beta";

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}
